// Generated by CoffeeScript 1.8.0

/*
slack.coffee: Test for instances of node-slack Transport
(C) 2015 Michael Brandenburg
MIT LICENCE
 */

(function() {
  var Slack, nodeSlack, util, winston;

  nodeSlack = require('node-slack');

  winston = require('winston');

  util = require('util');

  Slack = (function() {
    function Slack(options) {
      winston.Transport.call(this, options);
      options = options || {};
      this.name = "node-slack";
      this.token = options.token;
      this.team = options.team;
      this.channel = options.channel;
      this.slack = new nodeSlack(this.team, this.token);
      this.emoji = options.emoji || ":page_with_curl:";
      this.username = options.username || "Winston";
    }

    util.inherits(Slack, winston.Transport);

    winston.transports.Slack = Slack;

    Slack.prototype.name = "slack";

    Slack.prototype.get = function() {
      return this.token;
    };

    Slack.prototype.log = function(level, msg, meta, callback) {
      var self, slackJSON;
      if (this.silent) {
        return callback(null, true);
      }
      self = this;
      slackJSON = {
        text: msg,
        channel: this.channel
      };
      return callback(null, true);
    };

    return Slack;

  })();

  module.exports = Slack;

}).call(this);
